import React from 'react'
import Navbar from './Navbar'
import Head from 'next/head'

const Layout = ({children , title}) => {
  return (
    <div>
        <Head>
            <title>{title}</title>
        <title>InteriorDesigner</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar/>
      {children}
    </div>
  )
}

export default Layout